#ifndef ERRORS_H
#define ERRORS_H

enum ERRORS {
    NO_ERROR = 0,

    ERROR_REQUEST_INIT,
    ERROR_REQUEST_PERFORM,
    ERROR_REQUEST_HEADERS,
    ERROR_REQUEST_CLEANUP,

    ERROR_GET_IP_HAYSTACK_NOT_FOUND,
    ERROR_GET_IP_NEWLINE_NOT_FOUND,

    ERROR_HANDLE_ZONES_RESULT_NOT_ARRAY,
    ERROR_HANDLE_ZONES_SELECTOR_NOT_OBJECT,
    ERROR_HANDLE_ZONES_TYPE_NOT_STRING,
    ERROR_HANDLE_ZONES_ID_NOT_STRING,
    ERROR_HANDLE_ZONES_NAME_NOT_STRING,
};

#endif